/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as LibraryLocalRouteImport } from './routes/library-local'
import { Route as SeasonsRouteImport } from './routes/seasons'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as MediaMediaIdRouteImport } from './routes/media.$mediaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryLocalRoute = LibraryLocalRouteImport.update({
  id: '/library-local',
  path: '/library-local',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsRoute = SeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaMediaIdRoute = MediaMediaIdRouteImport.update({
  id: '/media/$mediaId',
  path: '/media/$mediaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/library-local': typeof LibraryLocalRoute
  '/seasons': typeof SeasonsRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/library-local': typeof LibraryLocalRoute
  '/seasons': typeof SeasonsRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/library-local': typeof LibraryLocalRoute
  '/seasons': typeof SeasonsRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/library-local'
    | '/seasons'
    | '/settings'
    | '/stats'
    | '/media/$mediaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/library-local'
    | '/seasons'
    | '/settings'
    | '/stats'
    | '/media/$mediaId'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/library-local'
    | '/seasons'
    | '/settings'
    | '/stats'
    | '/media/$mediaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  LibraryLocalRoute: typeof LibraryLocalRoute
  SeasonsRoute: typeof SeasonsRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  MediaMediaIdRoute: typeof MediaMediaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-local': {
      id: '/library-local'
      path: '/library-local'
      fullPath: '/library-local'
      preLoaderRoute: typeof LibraryLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons': {
      id: '/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof SeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$mediaId': {
      id: '/media/$mediaId'
      path: '/media/$mediaId'
      fullPath: '/media/$mediaId'
      preLoaderRoute: typeof MediaMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  LibraryLocalRoute: LibraryLocalRoute,
  SeasonsRoute: SeasonsRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  MediaMediaIdRoute: MediaMediaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
